name: E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Everyday at 1

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

jobs:

  minikube:
    name: K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.25.0, v1.24.0, v1.23.3, v1.22.6, v1.20.15, v1.19.16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.7.1
        with:
          minikube version: v1.28.0
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--force'
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install and Run Integration Tests
        run: |
          kubectl create -f src/main/resources/crd.yaml
          kubectl create clusterrolebinding default-pod --clusterrole cluster-admin --serviceaccount=default:default
          mvn clean install -Pe2e-kubernetes
