name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'ide-config/**'
      - '**.md'
  schedule:
    - cron: '0 1 * * *' # Every day at 1

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-e2e-podsetoperatorinjava-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

jobs:
  minikube_baremetal:
    name: Baremetal K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.25.0, v1.24.0, v1.23.3, v1.22.6, v1.20.15, v1.19.16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: v1.28.0
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--force'
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install and Run Integration Tests
        run: |
          kubectl create -f src/main/resources/crd.yaml
          kubectl create clusterrolebinding default-pod --clusterrole cluster-admin --serviceaccount=default:default
          mvn clean install -Pe2e-kubernetes

  minikube_docker:
    name: Docker K8S
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: [v1.27.3, v1.26.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: v1.30.1
          driver: docker
          container runtime: containerd
          kubernetes version: ${{ matrix.kubernetes }}
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--force'
      - name: Cache .m2 registry
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Install and Run Integration Tests
        run: |
          kubectl create -f src/main/resources/crd.yaml
          kubectl create clusterrolebinding default-pod --clusterrole cluster-admin --serviceaccount=default:default
          mvn clean install -Pe2e-kubernetes
